import type { JudgmentLab } from "./types";

/* Static sample content — authored and adversarially fact-checked.
   Review all materials for accuracy before classroom use. */

const data = {
  "intro": "Every activity in the Judgment Lab runs on one question: what does the bias DO? Not \"is this biased?\" — everything human or machine-made selects, frames, and compresses — but what a given framing amplifies, what it hides, what behavior it rewards, and what happens once someone acts on it. The Bias Consequence Ladder is our ten-rung tool for walking a framing from the artifact in front of you down to its real-world consequence: name the object of judgment, build a baseline from the source, mark the emphasis, mark the omission, name the mechanism, ask what the bias does, trace who benefits, trace the cost, test the action consequence, and state a correction and verdict. The ladder is deliberately not a verdict about whether something is \"good\" or \"bad.\" It is a mechanism trace, which is what keeps it nonpartisan: two students who disagree about an issue can still agree about what a summary emphasized or what a feed buried.\n\nThe AI and social-media age does not retire this work — it raises the stakes of skipping it. A machine summary, a ranked feed, and a chatbot's reply are all framings produced by a system optimizing for something (brevity, engagement, or your apparent intent), and each one hands you a fast, fluent, confident output that hides its own selection. Fluency is not fidelity, and confidence is not completeness. That is why all three labs share one spine and one principle: AI does not remove the need for judgment; it raises the cost of not having it. When an output is instant, polished, and personalized, the cost of accepting a flawed framing is paid faster, more invisibly, and at greater scale than ever before. The three labs move the object of judgment outward-to-inward: first a machine summary of a fixed historical source (Lab 1), then two machine-ranked feeds of the same neutral topic (Lab 2), and finally the student's own motivated reasoning as amplified by a mirror-like tool (Lab 3). Every AI example in this product is teacher-provided and pre-generated with an answer key; there is no live AI. The skill we are building is not \"spot the bias\" but \"trace the consequence\" — the habit of asking, before you believe or share or vote, what this framing would make me do.",
  "aiSummaryAudit": {
    "title": "The AI-Summary Audit",
    "overview": "Students run the full ten-step Bias Consequence Ladder on a teacher-provided AI-generated summary of a real historical primary source, checking the summary against the source it claims to represent. The premise: an AI summary is not the document — it is a framing of the document, produced by a system optimizing for brevity and readability, and it can be fluent, confident, and still structurally misleading. Students do not judge the amendment; they judge whether the summary is a faithful stand-in for it. The lab teaches the core Responsible-AI habit — never let a machine's summary replace the source it claims to compress — and turns 'what does the bias DO?' into a concrete audit of emphasis, omission, beneficiary, and consequence.",
    "setup": "Groups of two to four. Each group receives three things, all teacher-provided: (1) the full public-domain text of the primary source; (2) a single pre-written AI-style summary of that source — fluent and plausible but structurally skewed, supplied by the teacher, never generated live in class; and (3) the ten-rung Bias Consequence Ladder handout with space to write. Give students a highlighter for the summary and a different color for the source. Emphasize up front that this is an audit of a fixed artifact: the summary will not change, and the task is to check it against the source line by line. Budget roughly 40-55 minutes: read source, read summary, run the ladder, share verdicts. Close with each group stating a one-word verdict (faithful / flawed-but-usable / misleading) and defending it in one sentence.",
    "sourceUsed": "The Fourteenth Amendment to the U.S. Constitution (ratified 1868) — full text, all five sections. It is public domain and historically fixed, so every claim in the summary can be verified against the source itself. It is ideal because Section 1 (citizenship, due process, equal protection) is widely known while Sections 2 through 5 are widely unknown: Section 2 (apportionment and how representation is counted), Section 3 (disqualification from holding office for those who, having sworn an oath, engaged in insurrection), Section 4 (validity of the public debt and repudiation of Confederate debts), and Section 5 (congressional power to enforce). The gap between what a summary typically emphasizes and what the source actually contains is therefore authentic, historically grounded, and easy for students to check. A state 'declaration of causes' from 1860-61 works as an alternate source with the same audit structure. Keep the analysis on document structure and the mechanism of summarization, not on any present-day litigation.",
    "exampleSummaryNote": "For this exercise the teacher supplies a pre-written summary that is fluent, confident, and plausible — the kind of output a general-purpose model readily produces — but structurally skewed, paired with an answer key. It would open with and dwell on Section 1, casting the entire amendment as a broad moral guarantee of equality and citizenship in warm, absolute language. (An illustrative teacher-written line, offered only as a constructed example and NOT as an authentic or authoritative quotation, might read: 'The Fourteenth Amendment guarantees that all persons are equal and protected under the law.') It would then compress everything else to near-invisibility: apportionment (Section 2) reduced to a clause or dropped; the disqualification of former officeholders who engaged in insurrection (Section 3) omitted; the public-debt-validity and Confederate-debt-repudiation provisions (Section 4) omitted; and the congressional enforcement power (Section 5) omitted. The net effect is to present a five-part legal and political instrument as a one-part statement of values — technically 'accurate' about what it includes, misleading about proportion and scope. Present it to students explicitly as a constructed teaching artifact with an answer key, never as a real or trustworthy summary.",
    "steps": [
      "Name the object of judgment. Write down exactly what you are evaluating — the AI-generated summary — and what it claims to stand in for: the full text of the source. State plainly, 'I am not judging the amendment; I am judging whether this summary faithfully represents it.'",
      "Build the baseline from the source. Before rereading the summary, read the primary source itself and list its actual parts. For the Fourteenth Amendment, name all five sections and note the proportion — roughly how much of the document each section occupies. This is your ground truth.",
      "Mark the emphasis. Return to the summary and highlight what it foregrounds: what it leads with, what it repeats, and what it states in warm or absolute language. Note which single part of the source the summary treats as 'the point.'",
      "Mark the omission. Lay the summary beside the source and circle every provision in the source that the summary shrinks, blurs, or drops entirely. Name at least two sections a summary-only reader would never know exist.",
      "Name the mechanism. For each emphasis and each gap, identify HOW the framing operates: selection (which section was chosen), proportion (how much space it got), word choice (abstract and moral versus specific and procedural), and order (what came first). The bias lives in these levers, not in any false statement.",
      "Ask what the bias DOES. For the emphasis and the omission together, write the effect on a reader: what will a person who reads only this summary believe the source is and does? Write it as a sentence beginning 'A summary-only reader would conclude...'",
      "Trace who benefits. Ask cui bono — if readers accept this summary as the whole, whose preferred understanding is advanced and whose is erased? Answer strictly in terms of interests and understanding, never in terms of any party or present-day figure.",
      "Trace the cost. Name what is lost: which questions a citizen can no longer even think to ask, and which parts of the historical record become invisible, once the summary stands in for the source.",
      "Test the action consequence. Imagine two citizens — one acted on the summary, one read the source — facing a concrete moment (a debate, a vote, a claim in an essay). Describe where they would say or do different things, and which one gets caught unprepared and why.",
      "State the correction and the verdict. Write the one or two sentences you would add, or the reweighting you would demand, to make the summary faithful. Then deliver your judgment — faithful, flawed-but-usable, or misleading — and defend it in a single sentence tied to the mechanism you named."
    ],
    "questions": [
      "What did the summary emphasize, and by what mechanism (word choice, order, or proportion) did it make that emphasis feel like the whole point of the source?",
      "What did the summary omit or compress? Name at least two sections of the source that a summary-only reader would never know exist.",
      "Who benefits from the omission? Describe the beneficiary in terms of interests and understanding, not in terms of any party or modern figure.",
      "What happens if a citizen acts on the summary instead of the source? Give a concrete scenario where the missing sections would have changed what the citizen believed, said, or did.",
      "Would you call this summary faithful, flawed-but-usable, or misleading — and what single change would move it up one rung toward faithful?",
      "The summary was fluent and confident. Did that confidence tell you anything about its completeness? What does this reveal about using tone as a proxy for accuracy?"
    ],
    "exitTicket": "In two or three sentences: name one thing the AI summary made bigger than it is in the source, one thing it made smaller or invisible, and one specific decision a citizen might get wrong by trusting the summary over the source.",
    "teacherNote": "This lab operationalizes the Responsible-AI charge to evaluate machine-generated summaries against the primary sources they claim to represent. Everything is teacher-provided: you supply both the public-domain source text and a pre-written flawed summary, along with an answer key that lists the intended emphases and omissions in advance. Do NOT connect students to a live model — the point is auditing a fixed artifact, not generating new ones, and a live model would make the exercise unrepeatable and unverifiable. For the Fourteenth Amendment, your answer key should pre-identify the emphasis on Section 1's citizenship and equal-protection language and the omission of Section 2 (apportionment), Section 3 (disqualification from office for engaging in insurrection), Section 4 (public-debt validity and Confederate-debt repudiation), and Section 5 (enforcement). A specific administrator-safety note on Section 3: its disqualification-for-insurrection clause has been the subject of recent, real litigation, so handle it strictly as historical 1868 text. Do not name, allude to, or invite comparison with any specific current or recent official, candidate, party, or court case; if a student raises one, acknowledge briefly that the clause is contested today and steer immediately back to what the 1868 text actually says and what the summary DID to it. Keep discussion on the document's structure and the mechanism of summarization; if students drift toward present-day controversies, redirect to the neutral core question — 'what did this text actually say, and what did the summary DO to it?' The source is chosen precisely because nearly everyone knows Section 1 and almost no one knows the rest, so the omission is real, historically grounded, and checkable — which keeps the lab rigorous and administrator-safe."
  },
  "twoFeedsLab": {
    "title": "Two Feeds, One Topic",
    "overview": "Students receive two synthetic social-media feeds about the exact same fictional, neutral, local civic topic — one feed ranked to amplify outrage-driving signals, one ranked to amplify calm, useful ones — and analyze what each ranking amplifies, hides, and rewards. The twist that makes it rigorous: both feeds carry the identical set of underlying facts. Nothing is invented, and neither feed is 'lying.' The only variable is the sorting — what gets pushed to the top, what gets buried, and what behavior gets rewarded with visibility. Students learn to see the ranking mechanism itself as the thing doing the work, and to run 'what does the bias DO?' on an algorithm rather than on a claim — applying the Bias Consequence Ladder's mechanism-and-consequence trace to a ranking system instead of a single statement.",
    "scenario": "The fictional town of Alderton (population about 9,000) will vote on Measure B: whether to raise the monthly municipal water rate by $6 per household for ten years to fund structural repairs to the aging Larkspur Reservoir dam, which the town engineer has flagged in a public report as needing work within the decade. Supporters argue the repair prevents a far costlier emergency failure and protects the town's water supply. Opponents argue the flat rate hike falls hardest on fixed-income and renting households and favor a smaller, phased fix studied further first. Both positions are reasonable; the trade-off is real. There is no party, no real place, and no real person anywhere in the scenario — that is by design, so students study the ranking and not a national fight.",
    "setup": "Groups of two to four. Each group receives two teacher-provided synthetic feeds, printed or on slides — Feed A and Feed B — each showing roughly eight to ten posts about Measure B from fictional local accounts (e.g., '@AldertonNeighbor,' '@LarkspurWatch'). Both feeds contain the same core facts: the $6 figure, the ten-year term, the engineer's report, the supply-protection argument, and the burden-on-fixed-incomes argument. Feed A is ranked to reward outrage-driving signals: the angriest, most personal, most us-versus-them posts sit at the top — an all-caps accusation, a screenshot of a 'leaked' out-of-context quote, a countdown clock, a pile-on where the most cutting reply is the most visible; the engineer's actual numbers appear near the bottom. Feed B is ranked to reward calm, useful signals: the top posts are the engineer's plain-language summary, a neighbor asking a genuine clarifying question, a side-by-side cost table, and a 'here's what each side actually claims' post; usefulness and verifiability are what rise. Give each group a two-column annotation sheet: for each feed, mark what the ranking amplified, what it hid, and what behavior it rewarded. There is no live platform and no student social account involved — the feeds are fixed, synthetic teaching artifacts.",
    "questions": [
      "Same facts, two feeds. Name one fact that appears in BOTH feeds but feels completely different because of where and how the ranking placed it.",
      "What kind of post does Feed A push to the top, and what behavior does that reward in someone who wants to be seen or agreed with? Now answer the same two questions for Feed B.",
      "What does the outrage feed HIDE? Point to one fact, number, or question from the scenario that is technically present in Feed A but buried where few readers will ever reach it.",
      "Who or what benefits from the outrage ranking? Answer in terms of attention and engagement mechanics — not parties. Then: who or what benefits from the calm ranking?",
      "Run the recurring question on the algorithm: what does each feed's ranking DO to a voter's sense of the stakes, of the people on the other side, and of their own available options?",
      "Neither feed invented a single fact. If both are 'technically accurate,' what exactly is being manipulated? Name the lever in one phrase.",
      "Which feed would leave you better able to actually understand Measure B well enough to vote — and which would make you more likely to share a post before reading it? Why are those two different feeds?"
    ],
    "exitTicket": "In three sentences: name one thing the outrage feed amplified, one thing it hid, and one behavior it rewarded — then state which feed you would want running in your town the week before a real vote, and why.",
    "teacherNote": "Keep the topic fictional, local, and low-stakes on purpose. A reservoir vote or a school start-time debate carries a genuine trade-off but no partisan valence, which is exactly what lets students study the ranking mechanism instead of re-litigating a national issue. The non-negotiable design rule: both feeds must carry the identical set of facts, so the only independent variable is what the ranking amplifies, buries, and rewards. Provide both feeds pre-written, with an answer key that annotates, post by post, why the ranking placed it where it did — outrage signals to label include personalization, moral or tribal charge, novelty/leaks, and us-versus-them framing; calm signals include usefulness, clarification, and verifiability. One accuracy caveat to state plainly, so the lesson stays truthful rather than conspiratorial: real recommender systems are not programmed with an explicit 'outrage' switch. They optimize for engagement signals — clicks, comments, dwell time, shares — and outrage-laden content tends to win that competition because it reliably drives those signals. These two feeds deliberately exaggerate and separate that dynamic into a clean contrast so the mechanism is visible; describe them to students as engineered teaching artifacts, not literal screenshots of how any specific platform ranks. The harm to name is what an engagement objective rewards, not a hidden dial labeled 'make people angry.' Do NOT swap in a real town, measure, ballot, or public figure, and do not let students map the fictional sides onto real parties; if that starts, restate that the lesson is about the sorting algorithm, not the issue. There is no live platform and no student social media in this activity — the feeds are printed or slide-based synthetic artifacts, which keeps it de-identified, nonpartisan, and administrator-safe."
  },
  "runItOnYourself": {
    "title": "Run the Ladder on Yourself and the Machine",
    "overview": "The metacognitive capstone turns the ladder inward. In Lab 1 the biased artifact was a machine's summary; in Lab 2 it was a machine's ranking. Here the object of judgment becomes the student's own framing plus the machine's amplification of it. Working from a teacher-provided paired exchange, students compare how the same tool answers a leading question (one that smuggles a conclusion into the prompt) versus a neutral counter-question (one that asks for the strongest case on multiple sides plus what is still unknown). The pattern they are trained to see: a fluent tool tends to give back the shape of what it was asked — mirroring and amplifying the asker's premise. Students then run the ladder on that loop, judging two things at once: what the machine did with the framing, and what their own motivated reasoning did to produce the framing in the first place. The lesson lands the through-line: a tool that returns the shape of your question is most dangerous exactly when its answer feels most satisfying.",
    "steps": [
      "Read the paired prompts. Examine the two teacher-provided prompts about the same neutral topic — one leading (a loaded premise that asks the tool to justify a foregone conclusion) and one neutral (asks for the strongest arguments on more than one side, plus what is not yet known). Underline the words in the leading prompt that quietly smuggle in a conclusion.",
      "Predict before you compare. Before reading either output, write one sentence predicting how the two answers will differ. Recording your expectation now lets you check it honestly against the evidence in a moment.",
      "Compare the two provided outputs. Read the pre-generated answers side by side. Mark where the leading-prompt answer asserts without hedging, omits counter-evidence, or adopts the emotional charge of the premise; mark where the neutral-prompt answer surfaces trade-offs, multiple sides, and uncertainty.",
      "Run the ladder on the machine. Using rungs three through eight, name what the leading output amplified, what it omitted, the mechanism at work (it echoed and inflated your premise), and who or what that serves — here, it serves the belief you walked in with.",
      "Run the ladder on yourself. Now turn it around. Ask: why might I have wanted to ask the leading way? What conclusion was I hoping to have confirmed? Name your own motivated reasoning plainly and without shame — everyone has it, and noticing it is the whole skill.",
      "Test the action consequence. Write what you would have believed, said, or posted if you had only ever asked the leading question and trusted the answer. Then write what the neutral question let you see that the leading one hid.",
      "Write the correction. Draft one neutral prompt you could actually use next time on a topic you genuinely care about, and one concrete habit for checking any fluent answer against a real source before you act on it."
    ],
    "guardrail": "This lab is teacher-mediated and runs on PROVIDED example exchanges. The leading/neutral prompt pairs and their outputs are pre-generated by the teacher, printed on the handout, and paired with an answer key — they are not produced live in class. There is no live AI in this product: students do not connect to a public chatbot during the activity, so the exercise stays repeatable, verifiable, and administrator-safe. Topics must stay neutral and fictional or historical — a made-up town policy, a settled historical question, a low-stakes everyday choice — never a student's real personal conflict. And an absolute rule that holds even if a future school edition permits supervised generation on a walled, education-approved tool with teacher-entered prompts only: no private, personal, or identifying data about any student, family, or named person is ever typed into any public AI. The self-examination is about reasoning patterns, not disclosures.",
    "teacherNote": "The move here is metacognitive, not technical: the target is the student's own motivated reasoning as amplified by a mirror-like tool, not prompt-engineering craft. Pre-generate two or three prompt pairs on neutral topics and keep both the prompts and the outputs on the handout, so the classroom work is auditing rather than prompting. A brief accuracy note to keep the framing honest: the 'mirror' tendency (a model echoing and inflating a user's premise, sometimes called sycophancy) is a strong and well-documented pattern, but it is a tendency, not an iron law — say 'tends to' rather than 'always,' and let the pre-generated examples show the pattern rather than asserting it as inevitable. Normalize the self-examination hard — the aim is to make 'I asked it to agree with me' an ordinary noticing, not a confession, and to show that everyone's questions carry premises. Reinforce the capstone principle every group should be able to state by the end: AI does not remove the need for judgment; it raises the cost of not having it — and a tool that hands back the shape of your question is most dangerous precisely when its answer feels most satisfying. Keep it de-identified, off live AI, and on the provided exchanges."
  }
};

export const judgmentLab: JudgmentLab = data;
